// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6imGSA6L0wsQEzm6uH3Kr2XYxb0hP2bY',
    appId: '1:900631226978:web:62c45bb610086361f8ff3b',
    messagingSenderId: '900631226978',
    projectId: 'badmintonproject-3182c',
    authDomain: 'badmintonproject-3182c.firebaseapp.com',
    storageBucket: 'badmintonproject-3182c.firebasestorage.app',
    measurementId: 'G-4E904KF107',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzq3IU3I4lLmf7NcuM6olu-l8EYk9Dx8',
    appId: '1:900631226978:android:244e2f0ace1a8b66f8ff3b',
    messagingSenderId: '900631226978',
    projectId: 'badmintonproject-3182c',
    storageBucket: 'badmintonproject-3182c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPSH4M3ZjNu95uP-wxtAQcnaz9Pf393I',
    appId: '1:900631226978:ios:ae41374f6a1d9425f8ff3b',
    messagingSenderId: '900631226978',
    projectId: 'badmintonproject-3182c',
    storageBucket: 'badmintonproject-3182c.firebasestorage.app',
    iosBundleId: 'com.example.badmintonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDPSH4M3ZjNu95uP-wxtAQcnaz9Pf393I',
    appId: '1:900631226978:ios:ae41374f6a1d9425f8ff3b',
    messagingSenderId: '900631226978',
    projectId: 'badmintonproject-3182c',
    storageBucket: 'badmintonproject-3182c.firebasestorage.app',
    iosBundleId: 'com.example.badmintonProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6imGSA6L0wsQEzm6uH3Kr2XYxb0hP2bY',
    appId: '1:900631226978:web:dde506e0f589d69af8ff3b',
    messagingSenderId: '900631226978',
    projectId: 'badmintonproject-3182c',
    authDomain: 'badmintonproject-3182c.firebaseapp.com',
    storageBucket: 'badmintonproject-3182c.firebasestorage.app',
    measurementId: 'G-H7JLFKVVBM',
  );
}
